### ISSUE TITLE
Converter fails to parse perf.data files with PERF_SAMPLE_REGS_USER & PERF_SAMPLE_STACK_USER sample types.

### ISSUE THREAD

**Issue by romange** [google/perf_data_converter#70] opened 2018-12-16 14:04 UTC
When I run converter i get:
```
[ERROR:src/quipper/sample_info_reader.cc:277] PERF_SAMPLE_REGS_USER is not yet supported.
[ERROR:src/quipper/sample_info_reader.cc:591] Read/skipped 56 bytes, expected 8440 bytes.
[ERROR:src/perf_data_converter.cc:659] Could not read input perf.data
[FATAL:src/perf_to_profile.cc:27] Expected profile vector to have one element.
```

**Comment by aalexand** [comment] 2018-12-16 16:35
@romange Can you attach an example perf.data file?

**Comment by romange** [comment] 2018-12-16 16:50
@aalexand  Of course. Attached https://drive.google.com/file/d/1BeMmVjzDALt4jvdc8JtgEYFB9N5kHSDn/view?usp=sharing

**Comment by aalexand** [comment] 2018-12-16 20:18
@lannadorai PTAL

**Comment by lannadorai** [comment] 2018-12-17 20:37
The perf.data file is not parsed by the converter as the file contains the PERF_SAMPLE_REGS_USER and PERF_SAMPLE_STACK_USER perf sample types, which are not currently supported by quipper. We will address this error. Will update the issue once it is fixed.

FYI, the `dwarf` option to the --call-graph flag introduces the PERF_SAMPLE_REGS_USER and PERF_SAMPLE_STACK_USER sample types in the perf.data file. But the --call-graph flag options `fp` and `lbr` don't introduce these sample types in the perf.data file.

**Comment by aalexand** [comment] 2018-12-17 20:40
@lannadorai, should we change the error message in quipper to mention -g dwarf as the likely possible reason?

**Comment by ahh** [comment] 2019-07-30 16:15
@aalexand The error message change would be welcomed; it's possible to work it out if you know perf but not obvious.

Is there any ETA for supporting these sample types (and better yet --call-graph dwarf stacktracing?)

**Comment by aalexand** [comment] 2019-07-31 04:25
@ahh No ETA.

**Comment by ahh** [comment] 2020-05-22 04:03
I'd like to ping this; more and more systems are compiling sans frame pointers (I disagree with that decision but I don't always get to make it.) Dwarf backtrace support would be of exceptional value.

**Comment by aalexand** [comment] 2020-05-22 04:54
Unlikely we'll work on this soon, but I can review a patch if someone wants to put it together. The support should be off by default to keep the current behavior unchanged.

**Comment by ahh** [comment] 2020-05-22 05:03
I find the second half of that statement very surprising. The current
behavior is to crash on dwarf-y files.

**Comment by aalexand** [comment] 2020-05-22 05:12
The stack and the register data are potentially PII tainted, we have uses where I'd prefer to keep the current behavior.

**Comment by aengelas** [comment] 2021-03-19 17:48
I'm seeing something similar to this, I believe, but I'm unsure how to correct it. It looks like the issue is from `PERF_RECORD_TIME_CONV`; do you have any docs on which options need to be passed to `perf` to be compatible with this tool?

```sh
$ go tool pprof -web perf.data
Converting perf.data to a profile.proto... (May take a few minutes)
[WARNING:src/quipper/perf_reader.cc:1247] Skipping 104 bytes of metadata: HEADER_CPU_TOPOLOGY
[ERROR:src/quipper/perf_data_utils.cc:484] Non-zero remaining event size 24 received for event PERF_RECORD_TIME_CONV with no varaible payload event data or sample info data
[ERROR:src/quipper/perf_reader.cc:1095] Couldn't get variable payload size for event PERF_RECORD_TIME_CONV
[ERROR:src/quipper/perf_reader.cc:1023] Couldn't read event PERF_RECORD_TIME_CONV
[ERROR:src/perf_data_converter.cc:703] Could not read input perf.data
[FATAL:src/perf_to_profile.cc:33] Expected profile vector to have one element.
perf.data: failed to convert perf.data file. Try github.com/google/perf_data_converter: exit status 1
failed to fetch any source profiles
```

**Comment by aalexand** [comment] 2022-06-17 21:48
`PERF_RECORD_TIME_CONV` looks like a separate issue, let's not mix it into this one. This bug is about `PERF_SAMPLE_REGS_USER` and `PERF_SAMPLE_STACK_USER` which are present in the perf.data file when `--call-graph=dwarf` is used. This is a dupe of #105. To copy my note from there:

> At Google we do not use collection modes that can result in user mode register values to be recorded in the perf.data file. Hence the priority for us to work on this issue is low and we don't anticipate addressing or triaging it further soon.

So I'm closing this bug.

**Closed by aalexand** 2022-06-17 21:48 UTC
