### ISSUE TITLE
fips_break_test.h: No such file or directory

### ISSUE THREAD

**Issue by gschier** [google/perf_data_converter#115] opened 2022-02-16 01:54 UTC
When trying to compile this project on both Ubuntu 18.04 and Debian 9 operating systems, I get the following error:

```
external/boringssl/src/crypto/fipsmodule/bcm.c:32:10: fatal error: fips_break_test.h: No such file or directory
 #include "fips_break_test.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //src:perf_to_profile failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 68.100s, Critical Path: 9.56s
INFO: 534 processes: 8 internal, 526 processwrapper-sandbox.
```

Any ideas?

Thanks 🙏🏻

**Comment by s-kanev** [comment] 2022-02-18 22:33
I ran into this as well, trying to test an unrelated change to perf_data_converter.

It seems to be an issue with one of the dependencies -- [boringssl](https://github.com/google/perf_data_converter/blob/master/WORKSPACE#L37-L45), which we automatically fetch with bazel. `fips_break_test.h` was added there very [recently](https://boringssl-review.googlesource.com/c/boringssl/+/51329).

Looking at my attempted build, the file is there:
```
$ ls bazel-quipper/external/boringssl/src/crypto/fipsmodule/ | grep fips
fips_break_test.h
```
So, most like the change above was not tested with bazel, and the header needs to be added to a BUILD file somewhere in boringssl.

**Comment by s-kanev** [comment] 2022-02-22 19:34
This was fixed in boringssl with [this change](https://boringssl-review.googlesource.com/c/boringssl/+/51485). Confirmed a clean build works now (after a `bazel sync` to refetch dependencies).

**Closed by s-kanev** 2022-02-22 19:34 UTC
